# PATIENT INFORMATION & HEALTH INSURANCE COST
## **DATA TRANSFORMATION (3)**  
**Transformation non-numeric columns to numeric columns.**

In [1]:
import numpy as np
import pandas as pd

In [2]:
cleaned_data = pd.read_csv("cleaned_data.csv")
data = cleaned_data.copy()

data.head()

   Unnamed: 0  age     sex     bmi  children smoker     region      charges
0           0   19  female  27.900         0    yes  southwest  16884.92400
1           1   18    male  33.770         1     no  southeast   1725.55230
2           2   28    male  33.000         3     no  southeast   4449.46200
3           3   33    male  22.705         0     no  northwest  21984.47061
4           4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
data.drop(["Unnamed: 0"], axis = 1, inplace = True)

In [4]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
print("Total non-numeric columns:", len(data.select_dtypes("object").columns), "\n")

for column in data.select_dtypes("object").columns:
    print(column, ":", list(data[column].unique()),)

Total non-numeric columns: 3

sex : ['female', 'male']
smoker : ['yes', 'no']
region : ['southwest', 'southeast', 'northwest', 'northeast']

## **Label Encoding**  
**Label Encoding is a popular encoding technique for handling categorical variables. In this technique, each label is assigned a unique integer based on alphabetical ordering.**

In [6]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

data["sex"] = LE.fit_transform(data["sex"])
data["smoker"] = LE.fit_transform(data["smoker"])

|**sex**|**smoker**|  
|--------|----------|
| **0 : female**|**0 : no**|
| **1 : male**  | **1 : yes**|

In [7]:
data.head()

   age  sex     bmi  children  smoker     region      charges
0   19    0  27.900         0       1  southwest  16884.92400
1   18    1  33.770         1       0  southeast   1725.55230
2   28    1  33.000         3       0  southeast   4449.46200
3   33    1  22.705         0       0  northwest  21984.47061
4   32    1  28.880         0       0  northwest   3866.85520

## **One-Hot Encoding**  
**One-Hot Encoding is another popular technique for treating categorical variables. It simply creates additional features based on the number of unique values in the categorical feature. Every unique value in the category will be added as a feature.**

In [8]:
data = pd.get_dummies(data, columns = ["region"], prefix = ["region"], drop_first = True)

In [9]:
data.head()

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,1
1,18,1,33.770,1,0,1725.55230,0,1,0
2,28,1,33.000,3,0,4449.46200,0,1,0
3,33,1,22.705,0,0,21984.47061,1,0,0
4,32,1,28.880,0,0,3866.85520,1,0,0

### **Correlations Between Features**

In [10]:
corr = data.corr()
corr.style.background_gradient()

In [11]:
data.to_csv("final_data.csv")